import React from "react";
// import TwitterNavbar from "@/components/twitterNavbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./providers.js";

// Assuming Inter is a function that takes options
// and returns an object with a className property
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout is a React functional component
export default function RootLayout({
  children,
}) {
  return (
    // JSX code representing the HTML structure
    <html lang="en">
      <body className={`${inter.className} flex flex-row`}>
        <NextAuthProvider>
          {/* <TwitterNavbar /> */}
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
